#!/bin/bash

#PBS -q debug-g
#PBS -W group_list=gr88
#PBS -l select=1
#PBS -j oe

# cd ${PBS_O_WORKDIR}

export WANDB_API_KEY=889e27cabda8dcac57aafc382d47bc6b23c7635b

module load singularity/4.2.1
module load pytorch-gpu/2.6.0 



export model=unet-qb
export dataset=brain
export paradigm=v29_$dataset




echo $dataset

for noise in 1.0; do
  for eps in 1e+8; do
    for wf in 4; do
      for lswn in 32768; do
        for frcw in 0; do
          for plw in 1; do
            for fold in 0; do
              singularity exec --nv ~/pytorch.sif python ~/MedIAnomalyQB/reconstruction/train.py -d $dataset -m $model -g 0 -f $fold --epsilon $eps -p $paradigm --firing_rate_cost_weight $frcw --input-size 128 --perceptual_loss_weight $plw --wf $wf --latent_size_with_noise $lswn --noise $noise --train-weight-decay 0.001 --not_use_log_var --use_KL_divergence --rho 0.02 -bs 128;
            done
          done
        done
      done
    done
  done
done


